/**
 * Aéroports proposés à la saisie : « CODE|Ville|Pays ».
 *
 * Liste volontairement courte — les aéroports qu'un voyageur au départ du
 * Benelux a une chance de chercher. Elle sert à éviter les fautes de frappe,
 * pas à être exhaustive : un code IATA inconnu tapé à la main reste accepté.
 */

export default [
  // Belgique, Pays-Bas, Luxembourg
  "BRU|Bruxelles-Zaventem|Belgique", "CRL|Charleroi (Brussels South)|Belgique",
  "ANR|Anvers|Belgique", "LGG|Liège|Belgique", "OST|Ostende|Belgique",
  "AMS|Amsterdam-Schiphol|Pays-Bas", "EIN|Eindhoven|Pays-Bas",
  "RTM|Rotterdam|Pays-Bas", "MST|Maastricht|Pays-Bas", "GRQ|Groningue|Pays-Bas",
  "LUX|Luxembourg|Luxembourg",

  // France
  "CDG|Paris-Charles-de-Gaulle|France", "ORY|Paris-Orly|France", "BVA|Paris-Beauvais|France",
  "LYS|Lyon|France", "MRS|Marseille|France", "NCE|Nice|France", "TLS|Toulouse|France",
  "BOD|Bordeaux|France", "NTE|Nantes|France", "MPL|Montpellier|France", "LIL|Lille|France",
  "SXB|Strasbourg|France", "MLH|Bâle-Mulhouse|France", "RNS|Rennes|France", "BES|Brest|France",
  "CFE|Clermont-Ferrand|France", "GNB|Grenoble|France", "CMF|Chambéry|France",
  "TLN|Toulon|France", "NIM|Nîmes|France", "PGF|Perpignan|France", "BIQ|Biarritz|France",
  "PUF|Pau|France", "LDE|Tarbes-Lourdes|France", "EGC|Bergerac|France", "LRH|La Rochelle|France",
  "AJA|Ajaccio|France", "BIA|Bastia|France", "CLY|Calvi|France", "FSC|Figari|France",
  "PTP|Pointe-à-Pitre|Guadeloupe", "FDF|Fort-de-France|Martinique",
  "RUN|Saint-Denis de La Réunion|La Réunion", "CAY|Cayenne|Guyane",

  // Royaume-Uni et Irlande
  "LHR|Londres-Heathrow|Royaume-Uni", "LGW|Londres-Gatwick|Royaume-Uni",
  "STN|Londres-Stansted|Royaume-Uni", "LTN|Londres-Luton|Royaume-Uni",
  "LCY|Londres-City|Royaume-Uni", "SEN|Londres-Southend|Royaume-Uni",
  "MAN|Manchester|Royaume-Uni", "BHX|Birmingham|Royaume-Uni", "EDI|Édimbourg|Royaume-Uni",
  "GLA|Glasgow|Royaume-Uni", "BRS|Bristol|Royaume-Uni", "NCL|Newcastle|Royaume-Uni",
  "LPL|Liverpool|Royaume-Uni", "LBA|Leeds-Bradford|Royaume-Uni", "EMA|East Midlands|Royaume-Uni",
  "ABZ|Aberdeen|Royaume-Uni", "BFS|Belfast|Royaume-Uni", "CWL|Cardiff|Royaume-Uni",
  "SOU|Southampton|Royaume-Uni", "EXT|Exeter|Royaume-Uni", "INV|Inverness|Royaume-Uni",
  "JER|Jersey|Royaume-Uni", "DUB|Dublin|Irlande", "ORK|Cork|Irlande",
  "SNN|Shannon|Irlande", "NOC|Knock|Irlande", "KIR|Kerry|Irlande",

  // Allemagne, Suisse, Autriche
  "FRA|Francfort|Allemagne", "MUC|Munich|Allemagne", "BER|Berlin-Brandebourg|Allemagne",
  "DUS|Düsseldorf|Allemagne", "HAM|Hambourg|Allemagne", "CGN|Cologne-Bonn|Allemagne",
  "STR|Stuttgart|Allemagne", "HAJ|Hanovre|Allemagne", "NUE|Nuremberg|Allemagne",
  "LEJ|Leipzig|Allemagne", "BRE|Brême|Allemagne", "DTM|Dortmund|Allemagne",
  "FMM|Memmingen|Allemagne", "FKB|Karlsruhe-Baden|Allemagne", "PAD|Paderborn|Allemagne",
  "FDH|Friedrichshafen|Allemagne", "SCN|Sarrebruck|Allemagne", "HHN|Francfort-Hahn|Allemagne",
  "NRN|Weeze (Düsseldorf)|Allemagne",
  "ZRH|Zurich|Suisse", "GVA|Genève|Suisse", "BSL|Bâle|Suisse", "BRN|Berne|Suisse",
  "LUG|Lugano|Suisse",
  "VIE|Vienne|Autriche", "SZG|Salzbourg|Autriche", "INN|Innsbruck|Autriche",
  "GRZ|Graz|Autriche", "KLU|Klagenfurt|Autriche", "LNZ|Linz|Autriche",

  // Italie
  "FCO|Rome-Fiumicino|Italie", "CIA|Rome-Ciampino|Italie", "MXP|Milan-Malpensa|Italie",
  "LIN|Milan-Linate|Italie", "BGY|Milan-Bergame|Italie", "VCE|Venise|Italie",
  "TSF|Trévise|Italie", "BLQ|Bologne|Italie", "FLR|Florence|Italie", "PSA|Pise|Italie",
  "NAP|Naples|Italie", "BRI|Bari|Italie", "BDS|Brindisi|Italie", "CTA|Catane|Italie",
  "PMO|Palerme|Italie", "CAG|Cagliari|Italie", "OLB|Olbia|Italie", "AHO|Alghero|Italie",
  "TRN|Turin|Italie", "GOA|Gênes|Italie", "VRN|Vérone|Italie", "TRS|Trieste|Italie",
  "SUF|Lamezia Terme|Italie", "PSR|Pescara|Italie", "AOI|Ancône|Italie",

  // Espagne et Portugal
  "MAD|Madrid|Espagne", "BCN|Barcelone|Espagne", "AGP|Malaga|Espagne", "ALC|Alicante|Espagne",
  "VLC|Valence|Espagne", "SVQ|Séville|Espagne", "BIO|Bilbao|Espagne", "PMI|Palma de Majorque|Espagne",
  "IBZ|Ibiza|Espagne", "MAH|Minorque|Espagne", "LPA|Las Palmas (Grande Canarie)|Espagne",
  "TFS|Ténérife-Sud|Espagne", "TFN|Ténérife-Nord|Espagne", "ACE|Lanzarote|Espagne",
  "FUE|Fuerteventura|Espagne", "SPC|La Palma|Espagne", "GRO|Gérone|Espagne", "REU|Reus|Espagne",
  "SCQ|Saint-Jacques-de-Compostelle|Espagne", "OVD|Asturies|Espagne", "SDR|Santander|Espagne",
  "VGO|Vigo|Espagne", "LCG|La Corogne|Espagne", "ZAZ|Saragosse|Espagne", "RMU|Murcie|Espagne",
  "XRY|Jerez|Espagne",
  "LIS|Lisbonne|Portugal", "OPO|Porto|Portugal", "FAO|Faro|Portugal", "FNC|Madère|Portugal",
  "PDL|Ponta Delgada (Açores)|Portugal", "TER|Terceira (Açores)|Portugal",

  // Nord de l'Europe
  "CPH|Copenhague|Danemark", "AAL|Aalborg|Danemark", "BLL|Billund|Danemark",
  "ARN|Stockholm-Arlanda|Suède", "NYO|Stockholm-Skavsta|Suède", "BMA|Stockholm-Bromma|Suède",
  "GOT|Göteborg|Suède", "MMX|Malmö|Suède",
  "OSL|Oslo-Gardermoen|Norvège", "TRF|Oslo-Sandefjord|Norvège", "BGO|Bergen|Norvège",
  "SVG|Stavanger|Norvège", "TRD|Trondheim|Norvège", "TOS|Tromsø|Norvège",
  "HEL|Helsinki|Finlande", "TMP|Tampere|Finlande", "OUL|Oulu|Finlande", "RVN|Rovaniemi|Finlande",
  "KEF|Reykjavik|Islande",

  // Europe centrale et orientale
  "RIX|Riga|Lettonie", "TLL|Tallinn|Estonie", "VNO|Vilnius|Lituanie", "KUN|Kaunas|Lituanie",
  "WAW|Varsovie-Chopin|Pologne", "WMI|Varsovie-Modlin|Pologne", "KRK|Cracovie|Pologne",
  "GDN|Gdansk|Pologne", "WRO|Wroclaw|Pologne", "POZ|Poznan|Pologne", "KTW|Katowice|Pologne",
  "PRG|Prague|Tchéquie", "BRQ|Brno|Tchéquie", "BTS|Bratislava|Slovaquie", "KSC|Kosice|Slovaquie",
  "BUD|Budapest|Hongrie", "OTP|Bucarest|Roumanie", "CLJ|Cluj-Napoca|Roumanie",
  "TSR|Timisoara|Roumanie", "SOF|Sofia|Bulgarie", "VAR|Varna|Bulgarie", "BOJ|Bourgas|Bulgarie",
  "BEG|Belgrade|Serbie", "ZAG|Zagreb|Croatie", "SPU|Split|Croatie", "DBV|Dubrovnik|Croatie",
  "ZAD|Zadar|Croatie", "PUY|Pula|Croatie", "LJU|Ljubljana|Slovénie", "SJJ|Sarajevo|Bosnie",
  "SKP|Skopje|Macédoine du Nord", "TIA|Tirana|Albanie", "TGD|Podgorica|Monténégro",
  "TIV|Tivat|Monténégro",

  // Grèce, Chypre, Turquie, Malte
  "ATH|Athènes|Grèce", "SKG|Thessalonique|Grèce", "HER|Héraklion (Crète)|Grèce",
  "CHQ|La Canée (Crète)|Grèce", "RHO|Rhodes|Grèce", "CFU|Corfou|Grèce", "JMK|Mykonos|Grèce",
  "JTR|Santorin|Grèce", "KGS|Kos|Grèce", "ZTH|Zante|Grèce", "PVK|Preveza|Grèce",
  "KLX|Kalamata|Grèce", "LCA|Larnaca|Chypre", "PFO|Paphos|Chypre",
  "IST|Istanbul|Turquie", "SAW|Istanbul-Sabiha Gökçen|Turquie", "AYT|Antalya|Turquie",
  "ADB|Izmir|Turquie", "ESB|Ankara|Turquie", "DLM|Dalaman|Turquie", "BJV|Bodrum|Turquie",
  "MLA|Malte|Malte",

  // Proche et Moyen-Orient
  "DXB|Dubaï|Émirats arabes unis", "DWC|Dubaï-Al Maktoum|Émirats arabes unis",
  "AUH|Abou Dabi|Émirats arabes unis", "SHJ|Charjah|Émirats arabes unis",
  "DOH|Doha|Qatar", "KWI|Koweït|Koweït", "BAH|Bahreïn|Bahreïn", "MCT|Mascate|Oman",
  "RUH|Riyad|Arabie saoudite", "JED|Djeddah|Arabie saoudite", "AMM|Amman|Jordanie",
  "BEY|Beyrouth|Liban", "TLV|Tel-Aviv|Israël",

  // Afrique
  "CAI|Le Caire|Égypte", "HRG|Hurghada|Égypte", "SSH|Charm el-Cheikh|Égypte",
  "RMF|Marsa Alam|Égypte", "LXR|Louxor|Égypte",
  "CMN|Casablanca|Maroc", "RAK|Marrakech|Maroc", "AGA|Agadir|Maroc", "FEZ|Fès|Maroc",
  "TNG|Tanger|Maroc", "RBA|Rabat|Maroc",
  "TUN|Tunis|Tunisie", "DJE|Djerba|Tunisie", "MIR|Monastir|Tunisie",
  "ALG|Alger|Algérie", "ORN|Oran|Algérie", "CZL|Constantine|Algérie",
  "DKR|Dakar|Sénégal", "ABJ|Abidjan|Côte d'Ivoire", "ACC|Accra|Ghana", "LOS|Lagos|Nigeria",
  "ABV|Abuja|Nigeria", "DLA|Douala|Cameroun", "NSI|Yaoundé|Cameroun", "LBV|Libreville|Gabon",
  "BZV|Brazzaville|Congo", "FIH|Kinshasa|RD Congo", "LAD|Luanda|Angola",
  "NBO|Nairobi|Kenya", "MBA|Mombasa|Kenya", "JRO|Kilimandjaro|Tanzanie",
  "ZNZ|Zanzibar|Tanzanie", "DAR|Dar es Salaam|Tanzanie", "EBB|Entebbe|Ouganda",
  "KGL|Kigali|Rwanda", "ADD|Addis-Abeba|Éthiopie",
  "JNB|Johannesburg|Afrique du Sud", "CPT|Le Cap|Afrique du Sud", "DUR|Durban|Afrique du Sud",
  "WDH|Windhoek|Namibie", "MRU|Maurice|Maurice", "SEZ|Seychelles|Seychelles",
  "TNR|Antananarivo|Madagascar",

  // Asie
  "BKK|Bangkok-Suvarnabhumi|Thaïlande", "DMK|Bangkok-Don Muang|Thaïlande",
  "HKT|Phuket|Thaïlande", "CNX|Chiang Mai|Thaïlande", "USM|Koh Samui|Thaïlande",
  "KBV|Krabi|Thaïlande",
  "SIN|Singapour|Singapour", "KUL|Kuala Lumpur|Malaisie", "PEN|Penang|Malaisie",
  "LGK|Langkawi|Malaisie", "CGK|Jakarta|Indonésie", "DPS|Bali (Denpasar)|Indonésie",
  "SUB|Surabaya|Indonésie", "MNL|Manille|Philippines", "CEB|Cebu|Philippines",
  "HAN|Hanoï|Viêt Nam", "SGN|Hô Chi Minh-Ville|Viêt Nam", "DAD|Da Nang|Viêt Nam",
  "PNH|Phnom Penh|Cambodge", "REP|Siem Reap|Cambodge", "VTE|Vientiane|Laos",
  "RGN|Rangoun|Birmanie",
  "HKG|Hong Kong|Hong Kong", "MFM|Macao|Macao", "TPE|Taipei|Taïwan",
  "ICN|Séoul-Incheon|Corée du Sud", "GMP|Séoul-Gimpo|Corée du Sud", "PUS|Busan|Corée du Sud",
  "NRT|Tokyo-Narita|Japon", "HND|Tokyo-Haneda|Japon", "KIX|Osaka-Kansai|Japon",
  "ITM|Osaka-Itami|Japon", "NGO|Nagoya|Japon", "FUK|Fukuoka|Japon", "CTS|Sapporo|Japon",
  "OKA|Okinawa|Japon",
  "PEK|Pékin-Capital|Chine", "PKX|Pékin-Daxing|Chine", "PVG|Shanghai-Pudong|Chine",
  "SHA|Shanghai-Hongqiao|Chine", "CAN|Canton|Chine", "SZX|Shenzhen|Chine",
  "CTU|Chengdu|Chine", "XIY|Xi'an|Chine", "KMG|Kunming|Chine", "HGH|Hangzhou|Chine",
  "DEL|Delhi|Inde", "BOM|Mumbai|Inde", "BLR|Bangalore|Inde", "MAA|Chennai|Inde",
  "HYD|Hyderabad|Inde", "CCU|Calcutta|Inde", "COK|Kochi|Inde", "GOI|Goa|Inde",
  "TRV|Trivandrum|Inde", "AMD|Ahmedabad|Inde",
  "CMB|Colombo|Sri Lanka", "MLE|Malé|Maldives", "KTM|Katmandou|Népal", "DAC|Dacca|Bangladesh",
  "ISB|Islamabad|Pakistan", "KHI|Karachi|Pakistan", "LHE|Lahore|Pakistan",
  "TAS|Tachkent|Ouzbékistan", "ALA|Almaty|Kazakhstan", "NQZ|Astana|Kazakhstan",
  "GYD|Bakou|Azerbaïdjan", "TBS|Tbilissi|Géorgie", "EVN|Erevan|Arménie",

  // Amérique du Nord
  "JFK|New York-JFK|États-Unis", "EWR|New York-Newark|États-Unis", "LGA|New York-LaGuardia|États-Unis",
  "BOS|Boston|États-Unis", "PHL|Philadelphie|États-Unis", "IAD|Washington-Dulles|États-Unis",
  "DCA|Washington-Reagan|États-Unis", "BWI|Baltimore|États-Unis", "ATL|Atlanta|États-Unis",
  "MIA|Miami|États-Unis", "FLL|Fort Lauderdale|États-Unis", "MCO|Orlando|États-Unis",
  "TPA|Tampa|États-Unis", "CLT|Charlotte|États-Unis", "ORD|Chicago-O'Hare|États-Unis",
  "MDW|Chicago-Midway|États-Unis", "DTW|Détroit|États-Unis", "MSP|Minneapolis|États-Unis",
  "DEN|Denver|États-Unis", "DFW|Dallas-Fort Worth|États-Unis", "IAH|Houston|États-Unis",
  "AUS|Austin|États-Unis", "LAS|Las Vegas|États-Unis", "PHX|Phoenix|États-Unis",
  "SLC|Salt Lake City|États-Unis", "SAN|San Diego|États-Unis", "LAX|Los Angeles|États-Unis",
  "SFO|San Francisco|États-Unis", "SJC|San José (Californie)|États-Unis",
  "OAK|Oakland|États-Unis", "SEA|Seattle|États-Unis", "PDX|Portland|États-Unis",
  "HNL|Honolulu|États-Unis", "OGG|Maui|États-Unis", "ANC|Anchorage|États-Unis",
  "SJU|San Juan|Porto Rico",
  "YYZ|Toronto|Canada", "YUL|Montréal|Canada", "YVR|Vancouver|Canada", "YYC|Calgary|Canada",
  "YOW|Ottawa|Canada", "YEG|Edmonton|Canada", "YHZ|Halifax|Canada",
  "MEX|Mexico|Mexique", "CUN|Cancun|Mexique", "GDL|Guadalajara|Mexique",
  "MTY|Monterrey|Mexique", "SJD|Los Cabos|Mexique", "PVR|Puerto Vallarta|Mexique",

  // Caraïbes, Amérique centrale et du Sud
  "HAV|La Havane|Cuba", "VRA|Varadero|Cuba", "PUJ|Punta Cana|République dominicaine",
  "SDQ|Saint-Domingue|République dominicaine", "MBJ|Montego Bay|Jamaïque",
  "KIN|Kingston|Jamaïque", "NAS|Nassau|Bahamas", "BGI|Barbade|Barbade", "AUA|Aruba|Aruba",
  "CUR|Curaçao|Curaçao", "SXM|Saint-Martin|Saint-Martin",
  "PTY|Panama|Panama", "SJO|San José|Costa Rica", "LIR|Liberia|Costa Rica",
  "GUA|Guatemala|Guatemala", "SAL|San Salvador|Salvador",
  "BOG|Bogota|Colombie", "CTG|Carthagène|Colombie", "MDE|Medellin|Colombie",
  "UIO|Quito|Équateur", "GYE|Guayaquil|Équateur", "GPS|Galapagos|Équateur",
  "LIM|Lima|Pérou", "CUZ|Cuzco|Pérou", "LPB|La Paz|Bolivie", "VVI|Santa Cruz|Bolivie",
  "SCL|Santiago|Chili", "EZE|Buenos Aires-Ezeiza|Argentine", "AEP|Buenos Aires-Aeroparque|Argentine",
  "MVD|Montevideo|Uruguay", "ASU|Asuncion|Paraguay",
  "GRU|Sao Paulo-Guarulhos|Brésil", "CGH|Sao Paulo-Congonhas|Brésil", "GIG|Rio de Janeiro|Brésil",
  "SDU|Rio-Santos Dumont|Brésil", "BSB|Brasilia|Brésil", "SSA|Salvador de Bahia|Brésil",
  "REC|Recife|Brésil", "FOR|Fortaleza|Brésil", "MAO|Manaus|Brésil", "POA|Porto Alegre|Brésil",
  "CWB|Curitiba|Brésil", "NAT|Natal|Brésil",

  // Océanie
  "SYD|Sydney|Australie", "MEL|Melbourne|Australie", "BNE|Brisbane|Australie",
  "PER|Perth|Australie", "ADL|Adélaïde|Australie", "OOL|Gold Coast|Australie",
  "CNS|Cairns|Australie", "HBA|Hobart|Australie", "DRW|Darwin|Australie",
  "CBR|Canberra|Australie",
  "AKL|Auckland|Nouvelle-Zélande", "CHC|Christchurch|Nouvelle-Zélande",
  "WLG|Wellington|Nouvelle-Zélande", "ZQN|Queenstown|Nouvelle-Zélande",
  "NAN|Nadi|Fidji", "PPT|Papeete (Tahiti)|Polynésie française",
  "RAR|Rarotonga|Îles Cook", "NOU|Nouméa|Nouvelle-Calédonie", "VLI|Port-Vila|Vanuatu",
  "GUM|Guam|Guam", "POM|Port Moresby|Papouasie-Nouvelle-Guinée",
];
